spring:
  datasource:
    url: jdbc:postgresql://batyr.db.elephantsql.com:5432/qyhmeorl
    username: qyhmeorl
    password: ACxSlJn5fsmzsU4wi-86hDnE28tHOgOa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  address: 0.0.0.0
  port: 8080
